version: '3.8'

services:
  github-monitor:
#    build: .
    image: ghcr.io/driftywinds/hubrise
    container_name: hubrise
    ports:
      - "3035:5000"
    volumes:
      # Mount the database directory
      - ./data:/app/data
      # Optional: Mount static files for custom favicon
      #- ./static:/app/static
    environment:
      # Optional: Set a custom database path
      - DATABASE_PATH=/app/data/github_monitor.db
    restart: unless-stopped
    networks:
      - hubrise-net

networks:
  hubrise-net:
    driver: bridge
